### ISSUE TITLE
窗体尺寸最大化问题

### ISSUE THREAD

**Issue by MtGT90** [xingchuanzhen/Icon-conversion#2]
通过鼠标拖动窗体至屏幕边缘，可实现窗体的分屏或最大化，但该程序多出限制了布局容器的长宽属性，因此进行该操作会出现不可逆的问题。
解决办法：在主窗体增加ResizeMode="NoResize"属性

**Comment by Xing-Fax** [comment]
非常感谢您能提供此项目的软件问题，经过我的测试，的确发现此问题的存在，此问题的导致是我的疏忽大意，已采纳您的意见并将ResizeMode修改为NoResize，稍后您会看到新的更改被提交到项目中，最后再次感谢您提出的问题，谢谢！
